Repository ember-cli/ember-cli-app-version, pull requests merged in 2023-01, with the labels that each got.

#388 Drop support for Ember versions below v3.28, Drop support for Node versions below v14
  .ember-cli
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .template-lintrc.js
  .travis.yml
  CONTRIBUTING.md
  README.md
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  package.json
  tests/acceptance/index-test.js
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  tests/unit/helpers/app-version-test.js
  tests/unit/utils/regexp-test.js
  vendor/.gitkeep
  yarn.lock
Labels: breaking

#394 Upgrade `ember-source` to v4.9.3
  package.json
  yarn.lock
Labels: internal

#395 Upgrade `ember-resolver` to v9
  package.json
  yarn.lock
Labels: internal

#398 Remove use of `@ember/string` to avoid deprecation
  addon/initializer-factory.js
Labels: enhancement
